GUICtrlSetTip($inButton, "Chooses the IN Point for the A/B Loop")
GUICtrlSetTip($inTF, "The current position of the IN point for the A/B Loop")
GUICtrlSetTip($inDecButton, "Trims the IN point backwards a specific amount" & @CRLF & "(settable in 'Options' as the 'Slip Time Amount')")
GUICtrlSetTip($inIncButton, "Trims the IN point forwards a specific amount" & @CRLF & "(settable in 'Options' as the 'Slip Time Amount')")
GUICtrlSetTip($clearInButton, "Clears the IN point for the A/B Loop, resetting the loop's start time to 0:00")

GUICtrlSetTip($outButton, "Chooses the OUT Point for the A/B Loop")
GUICtrlSetTip($outTF, "The current position of the OUT point for the A/B Loop")
GUICtrlSetTip($outDecButton, "Trims the OUT point backwards a specific amount" & @CRLF & "(settable out 'Options' as the 'Slip Time Amount')")
GUICtrlSetTip($outIncButton, "Trims the OUT point forwards a specific amount" & @CRLF & "(settable out 'Options' as the 'Slip Time Amount')")
GUICtrlSetTip($clearOutButton, "Clears the OUT point for the A/B Loop, resetting the loop's end time to to the length of the current video")

GUICtrlSetTip($clearAllButton, "Clears both the IN and OUT points, resetting the loop to the entire length of the current video")
GUICtrlSetTip($timeTF, "The current playback time in MPC-HC or the remaining time of a loop -" & @CRLF & "Click on this to switch between current playback time in MPC-HC and the remaining time of the current loop")
GUICtrlSetTip($loopButton, "Click on this to change between looping modes - " & @CRLF & @CRLF & "'Loop Mode' - will loop the current IN and OUT points as a loop" & @CRLF & "'Playlist Mode' (if you have a playlist made) - loop through the playlist, one item at a time" & @CRLF & "'OFF' - MPC-HC acts like the Looper program isn't running, but you can still make IN and OUT points" & @CRLF & "and add them to the playlist, which is useful for EDL-like lists of IN and OUT points")
GUICtrlSetTip($optionsButton, "MPC-HC Looper settings, including preview time, slip time and options" & @CRLF & "to associate .looper files with Windows and save/restore default settings")
GUICtrlSetTip($OSDButton, "On-screen display (similar to Media Player Classic's OSD) that shows Loop Mode, the IN and OUT points, " & @CRLF & "the current playback position in Media Player Classic, the current event # (and the total # of events) " & @CRLF & "and the name of the current event" & @CRLF & @CRLF & "The transparent OSD window can also be moved by clicking and dragging to a new position")
GUICtrlSetTip($onTopButton, "Click on this to change whether MPC-HC Looper sits on top of all other windows" & @CRLF & "or acts like a normal window and disappears behind other windows")

GUICtrlSetTip($speedSlider, "Drag this slider to set the playback speed in MPC-HC")
GUICtrlSetTip($__SPD_025X, "Set playback to 25% of original speed")
GUICtrlSetTip($__SPD_05X, "Set playback to 50% of original speed")
GUICtrlSetTip($__SPD_075X, "Set playback to 75% of original speed")
GUICtrlSetTip($__SPD_1X, "Set playback to 100% (original) speed")
GUICtrlSetTip($__SPD_125X, "Set playback to 125% of original speed")
GUICtrlSetTip($__SPD_15X, "Set playback to 150% of original speed")
GUICtrlSetTip($__SPD_175X, "Set playback to 175% of original speed")
GUICtrlSetTip($__SPD_2X, "Set playback to 200% (twice original) speed")

GUICtrlSetTip($previousEventButton, "Load the previous event in the event list")
GUICtrlSetTip($nextEventButton, "Load the next event in the event list")

GUICtrlSetTip($eventList, "The current playlist - a list of seperate A/B Loops for the current session")
GUICtrlSetTip($listSaveButton, "Save the current playlist to a .looper file for later playback")
GUICtrlSetTip($listLoadButton, "Load a .looper file, saved from a previous session, into the playlist for playback")
GUICtrlSetTip($listDeleteButton, "Delete the current selected item from the playlist")
GUICtrlSetTip($listAddButton, "Add the current set of IN and OUT points to the playlist as a new event")
GUICtrlSetTip($listModifyButton, "Modify the current playlist item's IN and OUT points and (if needed) it's name")
GUICtrlSetTip($listClearButton, "Removes every item from the playlist and unloads the current .looper file -" & @CRLF & "restoring everything to 'like new' for a new session")

GUICtrlSetTip($HotKeyStatusTF, "Displays whether or not hotkeys (keyboard shortcuts) are:" & @CRLF & "Turned on (MPC-HC or the Looper program are active) or" & @CRLF & "Turned off (another window is active)")
GUICtrlSetTip($currentEventStatusTF, "Displays the current event's duration, or the duration of the entire playlist" & @CRLF & "Click on this to change between single event duration and total playlist duration")